# -*- coding: utf-8 -*-
"""Module End Assignment Python Customer Support Ticket Analyzer

Automatically generated by Colab.

**Project Title: Customer Support Ticket Analyser**

 In this project, you will build a Python-based Ticket Analysis System that stores, cleans, analyses, and extracts insights from customer support tickets.
"""

# DA-V8-M4 Python Assignment: Ticket Analysis System
ticket_data = {
    'Ticket_No': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Customer_Name': [ 'Ravi', 'Meera', 'Sam', 'Anu', 'Rakesh', 'Divya', 'Arjun', 'Kiran', 'Leela', 'Nisha'],
    'Issue_Description': [
        ' Internet not working!!! ',
        'slow response, very poor service ',
        'GREAT support! issue resolved.',
        ' okay... need help ',
        'not BAD but slow',
        'Excellent guidance, Very Helpful!',
        'good support and good behaviour!',
        'Poor handling of technical issue',
        'Satisfied. Could be better.',
        'Good service... quick response.'
    ],
  'Priority': ['High', 'Low', 'High', 'Medium', 'Low', 'High', 'Medium', 'High', 'Low', 'Medium']
    }
print("Initial Ticket Data:")
# display the tickets i create a function
def display_tickets(ticket_data):
  for i in range(len(ticket_data['Ticket_No'])):
    print(f"Ticket No: {ticket_data['Ticket_No'][i]:<3} : {ticket_data['Customer_Name'][i]:<10} - {ticket_data['Issue_Description'][i]:<40} - {ticket_data['Priority'][i]:<5}")
display_tickets(ticket_data)

Initial Ticket Data:
Ticket No: 1   : Ravi       -  Internet not working!!!                 - High 
Ticket No: 2   : Meera      - slow response, very poor service         - Low  
Ticket No: 3   : Sam        - GREAT support! issue resolved.           - High 
Ticket No: 4   : Anu        -  okay... need help                       - Medium
Ticket No: 5   : Rakesh     - not BAD but slow                         - Low  
Ticket No: 6   : Divya      - Excellent guidance, Very Helpful!        - High 
Ticket No: 7   : Arjun      - good support and good behaviour!         - Medium
Ticket No: 8   : Kiran      - Poor handling of technical issue         - High 
Ticket No: 9   : Leela      - Satisfied. Could be better.              - Low  
Ticket No: 10  : Nisha      - Good service... quick response.          - Medium

"""**Step 2: Add More Tickets**"""

add_more_tickets = int(input("How many new tickets do you want to add? "))
#add_more_tickets as number of times repeat the ticket collection

for i in range(add_more_tickets):
  add_more_customer = input("Enter Your Customer Name: ").capitalize()
  add_more_issue = input("Enter Your Issue Description: ")

  while True:
    add_more_priority = input("Enter your priority (High/Medium/Low): ").capitalize()
    if add_more_priority in ['High', 'Medium', 'Low']:
      break
    else:
      print("Invalid priority. Please enter High, Medium, or Low Only")

  #auto-increment ticket number
  last_ticket_no = ticket_data['Ticket_No'][-1]
  new_ticket_no = last_ticket_no + 1

  ticket_data['Ticket_No'].append(new_ticket_no)
  ticket_data['Customer_Name'].append(add_more_customer)
  ticket_data['Issue_Description'].append(add_more_issue)
  ticket_data['Priority'].append(add_more_priority)

print("\n Updated Ticket Datas for Customer Support:")
#recall the function
display_tickets(ticket_data)

How many new tickets do you want to add? 2
Enter Your Customer Name: Berlin
Enter Your Issue Description: good support
Enter your priority (High/Medium/Low): Medium
Enter Your Customer Name: priyan
Enter Your Issue Description: excellent work
Enter your priority (High/Medium/Low): high

 Updated Ticket Datas for Customer Support:
Ticket No: 1   : Ravi       -  Internet not working!!!                 - High 
Ticket No: 2   : Meera      - slow response, very poor service         - Low  
Ticket No: 3   : Sam        - GREAT support! issue resolved.           - High 
Ticket No: 4   : Anu        -  okay... need help                       - Medium
Ticket No: 5   : Rakesh     - not BAD but slow                         - Low  
Ticket No: 6   : Divya      - Excellent guidance, Very Helpful!        - High 
Ticket No: 7   : Arjun      - good support and good behaviour!         - Medium
Ticket No: 8   : Kiran      - Poor handling of technical issue         - High 
Ticket No: 9   : Leela      - Satisfied. Could be better.              - Low  
Ticket No: 10  : Nisha      - Good service... quick response.          - Medium
Ticket No: 11  : Berlin     - good support                             - Medium
Ticket No: 12  : Priyan     - excellent work                           - High 

"""**Step 3: Text Cleaning for Issue Descriptions**"""

punctuations = '.,!?*-'
replacements = [
    ('ok', 'okay'),
    ('okayay', 'okay'),
    ('okayayay', 'okay')
]

for i in range(len(ticket_data['Issue_Description'])):
    issue = ticket_data['Issue_Description'][i]

    # Step 1: Lowercase FIRST
    issue = issue.lower()

    # Step 2: Slang replacements (multiple)
    for old, new in replacements:
        issue = issue.replace(old, new)

    # Step 3: Remove punctuation
    for p in punctuations:
        issue = issue.replace(p, '')

    # Step 4: Fix spaces (multiple -> single, strip)
    issue = ' '.join(issue.split()).strip()

    ticket_data['Issue_Description'][i] = issue

print("Cleaned Issues Description:\n")
display_tickets(ticket_data)

Cleaned Issues Description:

Ticket No: 1   : Ravi       - internet not working                     - High 
Ticket No: 2   : Meera      - slow response very poor service          - Low  
Ticket No: 3   : Sam        - great support issue resolved             - High 
Ticket No: 4   : Anu        - okay need help                           - Medium
Ticket No: 5   : Rakesh     - not bad but slow                         - Low  
Ticket No: 6   : Divya      - excellent guidance very helpful          - High 
Ticket No: 7   : Arjun      - good support and good behaviour          - Medium
Ticket No: 8   : Kiran      - poor handling of technical issue         - High 
Ticket No: 9   : Leela      - satisfied could be better                - Low  
Ticket No: 10  : Nisha      - good service quick response              - Medium
Ticket No: 11  : Berlin     - good support                             - Medium
Ticket No: 12  : Priyan     - excellent work                           - High 


"""**Step 4: Keyword-Based Issue Insights**"""

def count_tickets_with_word(word):
  word = word.lower()
  count = 0
  for issue in ticket_data['Issue_Description']:
    if word in issue.lower():
      count += 1
  return count

print("Keyword Insights:")
keywords = ['poor', 'good', 'slow', 'excellent']
for keyword in keywords:
  count = count_tickets_with_word(keyword)
  print(f"Tickets with {keyword} : {count}")

  Keyword Insights:
Tickets with poor : 2
Tickets with good : 3
Tickets with slow : 2
Tickets with excellent : 2

"""**Step 5: Full Summary & Insights**"""

#1.	Display Final Cleaned ticket_data
print("=== FINAL CLEANED TICKET DATA ===")
display_tickets(ticket_data)

=== FINAL CLEANED TICKET DATA ===
Ticket No: 1   : Ravi       - internet not working                     - High 
Ticket No: 2   : Meera      - slow response very poor service          - Low  
Ticket No: 3   : Sam        - great support issue resolved             - High 
Ticket No: 4   : Anu        - okay need help                           - Medium
Ticket No: 5   : Rakesh     - not bad but slow                         - Low  
Ticket No: 6   : Divya      - excellent guidance very helpful          - High 
Ticket No: 7   : Arjun      - good support and good behaviour          - Medium
Ticket No: 8   : Kiran      - poor handling of technical issue         - High 
Ticket No: 9   : Leela      - satisfied could be better                - Low  
Ticket No: 10  : Nisha      - good service quick response              - Medium
Ticket No: 11  : Berlin     - good support                             - Medium
Ticket No: 12  : Priyan     - excellent work                           - High 


#2.	Priority Analysis
high_priority = ticket_data['Priority'].count('High')
medium_priority = ticket_data['Priority'].count('Medium')
low_priority = ticket_data['Priority'].count('Low')

print(f"High Priority: {high_priority} | Medium Priority: {medium_priority} | Low Priority: {low_priority}")
High Priority: 5 | Medium Priority: 4 | Low Priority: 3

#3.	Find the Ticket With the Longest Issue Description
word_counts = [len(issue.split()) for issue in ticket_data['Issue_Description']]
maximum_idx = word_counts.index(max(word_counts))
print(f"Ticket_No: #{ticket_data['Ticket_No'][maximum_idx]}")
print(f"Customer: {ticket_data['Customer_Name'][maximum_idx]}")
print(f"Issue: {ticket_data['Issue_Description'][maximum_idx]}")
print(f"Word count: {word_counts[maximum_idx]}")

Ticket_No: #2
Customer: Meera
Issue: slow response very poor service
Word count: 5

#4. Extract Unique Words Used
print("UNIQUE WORDS:")
unique_words = set()
for issue in ticket_data['Issue_Description']:
  words = unique_words.update(issue.split())
  unique_list = list(unique_words)
print(f"Total unique: {len(unique_list)}")
print(f"Unique words: {unique_list}")

UNIQUE WORDS:
Total unique: 32
Unique words: ['service', 'support', 'be', 'excellent', 'guidance', 'helpful', 'working', 'slow', 'response', 'great', 'not', 'poor', 'better', 'behaviour', 'bad', 'help', 'could', 'handling', 'internet', 'technical', 'issue', 'good', 'satisfied', 'very', 'and', 'of', 'but', 'work', 'need', 'quick', 'okay', 'resolved']

